#!/usr/bin/env python3
"""Reference generator: ALG-08 (distributive law), type NE (expression entry).

Shows the pattern every generator should follow:
  * fixed random seed, so the same call always gives the same items
  * the correct answer is COMPUTED (sympy), never typed by hand
  * the typical wrong answer is computed from the misconception rule
    ("multiplier applied to the first term only")
  * output is a list of schema-conformant items; the caller wraps them in
    {schema_version, topic, type, items} and writes exercises/ALG-08/NE.json

This file is an example. Real cells are generated by the scheduled routine.
Usage:  python generators/example_alg08_ne.py --run 1 --date 2026-10-01 > items.json
"""
import argparse
import json
import random

import sympy as sp

TEMPLATE = "example_alg08_ne"
x = sp.Symbol("x")
SAMPLES = [[-2], [0], [3]]


def fmt(expr):
    """Plain Unicode text for Telegram and apps: 2x + 6, 6x − 12."""
    return str(expr).replace("*", "").replace("-", "−")


def make_items(run, date, count=5, start=1):
    rng = random.Random(8)  # fixed seed
    items, seen = [], set()
    while len(items) < count:
        level = "T" if len(items) < 3 else "H"
        a, b = rng.randint(2, 9), rng.randint(2, 9)
        c = 1 if level == "T" else rng.randint(2, 5)
        sign = 1 if level == "T" and len(items) % 2 == 0 else -1
        inner = c * x + sign * b
        if (a, b, c, sign) in seen:
            continue
        seen.add((a, b, c, sign))
        correct = sp.expand(a * inner)
        wrong_first_term_only = a * c * x + sign * b  # the misconception
        wrong_sign = a * c * x - sign * a * b  # sign slip
        assert sp.expand(correct - wrong_first_term_only) != 0
        assert sp.expand(correct - wrong_sign) != 0
        text_inner = f"{'' if c == 1 else c}x {'+' if sign > 0 else '−'} {b}"
        n = start + len(items)
        items.append({
            "schema_version": "1.0",
            "id": f"ALG-08-NE-{n:03d}",
            "type": "NE",
            "status": "draft",
            "lang": "fi",
            "curriculum": {"ops": ["S3.02"], "t": ["T14"], "grade": 7, "level": level},
            "misconceptions": ["ALG-08"],
            "prompt": {"text": f"Avaa sulut ja sievennä: {a}({text_inner})"},
            "payload": {
                "answer": {"kind": "expression", "variables": ["x"], "reference": fmt(correct), "samples": SAMPLES},
                "wrong": [
                    {"match": fmt(wrong_first_term_only), "misconception": "ALG-08",
                     "feedback": f"Kerroin {a} kertoo myös sulun jälkimmäisen termin."},
                    {"match": fmt(wrong_sign), "misconception": "ALG-07",
                     "feedback": "Tarkista jälkimmäisen termin merkki kertolaskun jälkeen."},
                ],
                "input_hint": "Kirjoita esim. 2x + 6",
            },
            "solution": {"steps": [f"{a} · {sp.Integer(c) * x if c != 1 else x} + {a} · ({sign * b})", fmt(correct)],
                         "final": fmt(correct)},
            "feedback": {"correct": "Oikein: kerroin kertoo jokaisen sulun sisällä olevan termin."},
            "provenance": {"template": TEMPLATE, "params": {"a": a, "b": b, "c": c, "sign": sign},
                           "generated": date, "verified": True, "run": run},
        })
    return items


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", type=int, default=1)
    ap.add_argument("--date", default="2026-10-01")
    ap.add_argument("--count", type=int, default=5)
    args = ap.parse_args()
    print(json.dumps(make_items(args.run, args.date, args.count), ensure_ascii=False, indent=2))
