// Builds data/goals.json from the curriculum goal files (read only):
//   math-misconceptions/grades1-6/data/curriculum/OPS_1-6_oppimistavoitteet.md  (A12.*, A36.*)
//   math-applets/math/OPS_7-9_oppimistavoitteet.md                               (S*.*)
// Goals are the table rows of section 3 ("Atomiset oppimistavoitteet").
//
//   node tools/build_goals.js          write data/goals.json
//   node tools/build_goals.js --check  exit 1 if it is out of date

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SITE_DIR = path.resolve(HERE, '..');
const REPO_ROOT = path.resolve(SITE_DIR, '..');
export const GOALS_PATH = path.join(SITE_DIR, 'data', 'goals.json');

const SOURCES = [
  'math-misconceptions/grades1-6/data/curriculum/OPS_1-6_oppimistavoitteet.md',
  'math-applets/math/OPS_7-9_oppimistavoitteet.md',
];
const ROW = /^\|\s*((?:A12|A36)\.S\d\.\d{2}|S\d\.\d{2})\s*\|([^|]+)\|(.*)\|\s*$/;
const AREA = /^#{3,4}\s+(S\d)\s+(.+?)\s*$/;

function band(id) {
  if (id.startsWith('A12.')) return '1-2';
  if (id.startsWith('A36.')) return '3-6';
  return '7-9';
}

export function parseGoals(markdown) {
  const goals = {};
  const lines = markdown.split(/\r?\n/);
  let inSection = false;
  let area = null;
  for (const line of lines) {
    if (/^## /.test(line)) {
      inSection = /^## 3\./.test(line);
      continue;
    }
    if (!inSection) continue;
    const a = AREA.exec(line);
    if (a) {
      area = `${a[1]} ${a[2]}`;
      continue;
    }
    const m = ROW.exec(line);
    if (!m || goals[m[1]]) continue;
    const id = m[1];
    const rest = m[3].split('|').map((c) => c.trim());
    const goal = { text: m[2].trim(), band: band(id), area };
    // The 7-9 table has a grade column before the T-goals.
    if (goal.band === '7-9' && rest[0] && /\d/.test(rest[0])) goal.grade = rest[0];
    goals[id] = goal;
  }
  return goals;
}

export function buildGoals(root = REPO_ROOT) {
  const goals = {};
  for (const rel of SOURCES) {
    const p = path.join(root, rel);
    if (!fs.existsSync(p)) continue;
    Object.assign(goals, parseGoals(fs.readFileSync(p, 'utf8')));
  }
  const sorted = Object.keys(goals).sort((a, b) => a.localeCompare(b, 'fi', { numeric: true }));
  return {
    schema_version: 1,
    note: 'Generated by tools/build_goals.js from the curriculum goal files. Do not edit by hand.',
    goals: Object.fromEntries(sorted.map((id) => [id, goals[id]])),
  };
}

export function serialize(data) {
  return JSON.stringify(data, null, 2) + '\n';
}

function main(argv) {
  const text = serialize(buildGoals());
  if (argv.includes('--check')) {
    const current = fs.existsSync(GOALS_PATH) ? fs.readFileSync(GOALS_PATH, 'utf8') : '';
    if (current !== text) {
      console.error('data/goals.json is out of date. Run: node tools/build_goals.js');
      process.exit(1);
    }
    console.log('goals OK');
    return;
  }
  fs.writeFileSync(GOALS_PATH, text);
  console.log(`wrote data/goals.json: ${Object.keys(JSON.parse(text).goals).length} goals`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
