// Builds data/manifest.json: the list of exercise files the practice pages
// load, with item counts. GitHub Pages cannot list folders, so the pages
// need this list. Reads the exercise pipelines' files, never edits them.
//
//   node tools/build_manifest.js          write data/manifest.json
//   node tools/build_manifest.js --check  exit 1 if it is out of date

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const SITE_DIR = path.resolve(HERE, '..');
export const REPO_ROOT = path.resolve(SITE_DIR, '..');
export const MANIFEST_PATH = path.join(SITE_DIR, 'data', 'manifest.json');

const SOURCES = [
  { format: 'grades1-6', dir: 'math-misconceptions/grades1-6/exercises/grades1-6', pattern: /^batch-.*\.json$/, depth: 1 },
  { format: 'grades7-9', dir: 'math-misconceptions/exercises', pattern: /^[A-Z]{2,3}\.json$/, depth: 2 },
];

function listFiles(root, source) {
  const base = path.join(root, source.dir);
  if (!fs.existsSync(base)) return [];
  const dirs = source.depth === 1
    ? [base]
    : fs.readdirSync(base, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => path.join(base, d.name));
  return dirs
    .flatMap((d) => fs.readdirSync(d).filter((f) => source.pattern.test(f)).map((f) => path.join(d, f)))
    .map((f) => path.relative(root, f).split(path.sep).join('/'))
    .sort();
}

function itemsOf(format, data) {
  if (format === 'grades1-6') return Array.isArray(data) ? data : [];
  return data && Array.isArray(data.items) ? data.items : [];
}

function goalsOf(format, item) {
  if (format === 'grades1-6') return item.goal ? [item.goal] : [];
  return (item.curriculum && item.curriculum.ops) || [];
}

function misconceptionsOf(format, item) {
  if (format === 'grades1-6') return item.workbook || [];
  return item.misconceptions || [];
}

function bump(counter, key) {
  counter[key] = (counter[key] || 0) + 1;
}

function sortKeys(obj) {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

export function buildManifest(root = REPO_ROOT) {
  const files = [];
  const totals = { items: 0, by_status: {}, by_goal: {}, by_misconception: {} };
  for (const source of SOURCES) {
    for (const rel of listFiles(root, source)) {
      const data = JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
      const items = itemsOf(source.format, data);
      const byStatus = {};
      for (const item of items) {
        bump(byStatus, item.status || 'unknown');
        bump(totals.by_status, item.status || 'unknown');
        for (const g of goalsOf(source.format, item)) bump(totals.by_goal, g);
        for (const m of misconceptionsOf(source.format, item)) bump(totals.by_misconception, m);
      }
      totals.items += items.length;
      // Paths relative to harjoittele/, ready for fetch() from the pages.
      files.push({ path: `../${rel}`, format: source.format, items: items.length, by_status: sortKeys(byStatus) });
    }
  }
  return {
    schema_version: 1,
    note: 'Generated by tools/build_manifest.js. Do not edit by hand.',
    files,
    totals: {
      items: totals.items,
      by_status: sortKeys(totals.by_status),
      by_goal: sortKeys(totals.by_goal),
      by_misconception: sortKeys(totals.by_misconception),
    },
  };
}

export function serialize(manifest) {
  return JSON.stringify(manifest, null, 2) + '\n';
}

function main(argv) {
  const text = serialize(buildManifest());
  if (argv.includes('--check')) {
    const current = fs.existsSync(MANIFEST_PATH) ? fs.readFileSync(MANIFEST_PATH, 'utf8') : '';
    if (current !== text) {
      console.error('data/manifest.json is out of date. Run: node tools/build_manifest.js');
      process.exit(1);
    }
    console.log('manifest OK');
    return;
  }
  fs.mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  fs.writeFileSync(MANIFEST_PATH, text);
  const m = JSON.parse(text);
  console.log(`wrote data/manifest.json: ${m.files.length} files, ${m.totals.items} items`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
