#!/usr/bin/env python3
"""Collects the misconception catalogue into data/misconceptions_source.json.

Sources (read only):
  math-misconceptions/sources/math_misconceptions_item_bank.xlsx  sheet "Misconceptions"
  math-misconceptions/math-misconceptions-7-9grades-backlog.md     section 3.2 (EXT topics)
  math-misconceptions/grades1-6/tools/buggy_rules/buggy_rules.py  RULES (sub-variants such as NUM-10a)

The output is English reference text. The Finnish pupil and teacher texts are
written by hand in data/misconceptions_fi.json; the unit tests check that both
files cover the same ids. Standard library only.

Usage:  python3 tools/extract_misconceptions.py            write the file
        python3 tools/extract_misconceptions.py --check    exit 1 if out of date
"""
import ast
import json
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
REPO = SITE.parent
XLSX = REPO / "math-misconceptions/sources/math_misconceptions_item_bank.xlsx"
BACKLOG = REPO / "math-misconceptions/math-misconceptions-7-9grades-backlog.md"
BUGGY = REPO / "math-misconceptions/grades1-6/tools/buggy_rules/buggy_rules.py"
OUT = SITE / "data/misconceptions_source.json"

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
REL = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id"
COLUMNS = {
    "ID": "id", "Strand": "strand", "Topic": "topic", "Misconception": "name",
    "Description": "description", "Illustrative item (stem)": "example",
    "Correct answer": "correct", "Typical wrong answer (distractor)": "typical_wrong",
    "Why students choose it": "why", "Evidence strength": "evidence",
}


def col_index(ref):
    letters = re.match(r"[A-Z]+", ref).group(0)
    n = 0
    for c in letters:
        n = n * 26 + ord(c) - 64
    return n - 1


def read_sheet(path, name):
    with zipfile.ZipFile(path) as z:
        shared = []
        if "xl/sharedStrings.xml" in z.namelist():
            for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS):
                shared.append("".join(t.text or "" for t in si.iter(f"{{{NS['m']}}}t")))
        wb = ET.fromstring(z.read("xl/workbook.xml"))
        rid = next(s.get(REL) for s in wb.find("m:sheets", NS) if s.get("name") == name)
        rels = ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))
        target = next(r.get("Target") for r in rels if r.get("Id") == rid)
        sheet = ET.fromstring(z.read("xl/" + target.lstrip("/").removeprefix("xl/")))
    rows = []
    for row in sheet.find("m:sheetData", NS):
        values = {}
        for c in row:
            v = c.find("m:v", NS)
            if c.get("t") == "s" and v is not None:
                text = shared[int(v.text)]
            elif c.get("t") == "inlineStr":
                text = "".join(t.text or "" for t in c.iter(f"{{{NS['m']}}}t"))
            else:
                text = v.text if v is not None else ""
            values[col_index(c.get("r"))] = text
        if values:
            rows.append([values.get(i, "") for i in range(max(values) + 1)])
    return rows


def from_xlsx():
    rows = read_sheet(XLSX, "Misconceptions")
    header = rows[0]
    out = []
    for r in rows[1:]:
        rec = {COLUMNS[h]: (r[i].strip() if i < len(r) else "") for i, h in enumerate(header) if h in COLUMNS}
        if rec.get("id"):
            out.append({"source": "xlsx", **rec})
    return out


def from_backlog():
    text = BACKLOG.read_text(encoding="utf-8")
    section = text.split("### 3.2", 1)[1].split("\n## ", 1)[0]
    out = []
    for line in section.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 5 and re.fullmatch(r"EXT-\d{2}", cells[0]):
            out.append({"source": "backlog-7-9", "id": cells[0], "name": cells[1],
                        "typical_wrong": cells[3], "correct": cells[4]})
    return out


def from_buggy_rules():
    tree = ast.parse(BUGGY.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", "") == "RULES" for t in node.targets):
            rules = ast.literal_eval(node.value)
            # Only sub-variants (NUM-10a); plain ids are already in the xlsx.
            return [{"source": "buggy_rules", "id": k, "name": v, "parent": k[:-1]}
                    for k, v in rules.items() if re.fullmatch(r"[A-Z]{3}-\d{2}[a-z]", k)]
    raise SystemExit("RULES not found in buggy_rules.py")


def build():
    records = from_xlsx() + from_backlog() + from_buggy_rules()
    ids = [r["id"] for r in records]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        raise SystemExit(f"duplicate ids: {dupes}")
    return {
        "schema_version": 1,
        "note": "Generated by tools/extract_misconceptions.py. English reference only; do not edit by hand.",
        "misconceptions": sorted(records, key=lambda r: r["id"]),
    }


def main(argv):
    data = build()
    text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("data/misconceptions_source.json is out of date. Run: python3 tools/extract_misconceptions.py")
            return 1
        print("misconceptions source OK")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote data/misconceptions_source.json: {len(data['misconceptions'])} records")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
